### ISSUE TITLE
Click off to close does not work for the index.html screen

### ISSUE THREAD

**Issue by heatherknoyes** [bnicp/recall-near-me#83]

**Comment by rekhawb** [comment]
15-vizs-chartAddition-mapFixes](https://github.com/bnicp/recall-near-me/tree/15-vizs-chartAddition-mapFixes

Event.stoppropogation() was added in the code, to stop category button click propogation to the parent node. Due to this change, window.Onclick was not functional for searchModal box. commenting event.stoppropogation() fixed the functionality
